pipeline:
  Run preprocessor tests:
    image: corylogan/node_python:0.0.1
    commands:
      - cd preprocessing
      - npm install
      - npm test

  # Run ember tests:

notify:
  downstream:
    image: plugins/downstream
    server: https://drone.flirtmoji.co
    repositories:
      - corylogan/homepage
    # secrets: [ DRONE_TOKEN ]
    # token: ${DRONE_TOKEN}
    when:
      event: push
      branch: master
      success: true
