pipeline:
  Run preprocessor tests:
    image: corylogan/node_python:0.0.1
    commands:
      - cd preprocessing
      - echo "installing node modules, this will take a moment"
      - npm install --silent
      - npm test

  Trigger homepage build:
    image: corylogan/simple-drone-trigger:0.0.6
    pull: true
    secrets: [ DRONE_TOKEN, DRONE_SERVER ]
    environment:
      - DRONE_SERVER=${DRONE_SERVER}
      - DRONE_TOKEN=${DRONE_TOKEN}
      - REPOSITORY=counterbeing/homepage
    # when:
    #   event: push
    #   branch: master
    #   success: true
